import '../scan_result.dart';
import 'reporter.dart';

/// Dark-themed HTML reporter for shareable audit reports.
class HtmlReporter extends Reporter {
  @override
  String format(ScanResult result) {
    final buf = StringBuffer();
    buf.writeln('<!DOCTYPE html>');
    buf.writeln('<html lang="en"><head>');
    buf.writeln('<meta charset="UTF-8">');
    buf.writeln('<meta name="viewport" content="width=device-width, initial-scale=1.0">');
    buf.writeln('<title>Security Scan Report — flutter_neo_shield</title>');
    buf.writeln('<style>');
    buf.writeln(_css);
    buf.writeln('</style></head><body>');

    // Header
    buf.writeln('<div class="header">');
    buf.writeln('<h1>flutter_neo_shield Security Report</h1>');
    buf.writeln('<p class="meta">Project: ${_esc(result.projectPath)} | Mode: ${result.scanMode} | '
        'Files: ${result.filesScanned} | Duration: ${result.duration.inMilliseconds}ms</p>');
    buf.writeln('</div>');

    // Score card
    final gradeClass = result.score >= 80 ? 'pass' : (result.score >= 60 ? 'warn' : 'fail');
    buf.writeln('<div class="score-card $gradeClass">');
    buf.writeln('<div class="score">${result.score}</div>');
    buf.writeln('<div class="grade">Grade ${result.grade}</div>');
    buf.writeln('<div class="status">${result.passed ? "PASSED" : "FAILED"}</div>');
    buf.writeln('</div>');

    // Summary
    buf.writeln('<div class="summary">');
    buf.writeln('<div class="stat critical"><span class="num">${result.criticalCount}</span><span class="label">Critical</span></div>');
    buf.writeln('<div class="stat high"><span class="num">${result.highCount}</span><span class="label">High</span></div>');
    buf.writeln('<div class="stat medium"><span class="num">${result.mediumCount}</span><span class="label">Medium</span></div>');
    buf.writeln('<div class="stat low"><span class="num">${result.lowCount}</span><span class="label">Low</span></div>');
    buf.writeln('<div class="stat info"><span class="num">${result.infoCount}</span><span class="label">Info</span></div>');
    buf.writeln('</div>');

    // Findings by category
    if (result.findings.isNotEmpty) {
      final byCategory = result.findingsByCategory;
      for (final entry in byCategory.entries) {
        buf.writeln('<div class="category">');
        buf.writeln('<h2>${_esc(entry.key)} <span class="count">(${entry.value.length})</span></h2>');
        buf.writeln('<table><thead><tr>');
        buf.writeln('<th>Severity</th><th>Rule</th><th>File</th><th>Line</th><th>Description</th><th>Fix</th>');
        buf.writeln('</tr></thead><tbody>');
        for (final f in entry.value) {
          buf.writeln('<tr class="${f.severity.name}">');
          buf.writeln('<td><span class="badge ${f.severity.name}">${f.severity.label}</span></td>');
          buf.writeln('<td>${_esc(f.ruleId)}</td>');
          buf.writeln('<td>${_esc(f.filePath)}</td>');
          buf.writeln('<td>${f.lineNumber}</td>');
          buf.writeln('<td>${_esc(f.title)}</td>');
          buf.writeln('<td>${_esc(f.rule.recommendation)}</td>');
          buf.writeln('</tr>');
        }
        buf.writeln('</tbody></table></div>');
      }
    } else {
      buf.writeln('<div class="no-findings">No security issues found.</div>');
    }

    // Footer
    buf.writeln('<div class="footer">');
    buf.writeln('Generated by flutter_neo_shield v2.1.1 Security Scanner');
    buf.writeln('</div>');

    buf.writeln('</body></html>');
    return buf.toString();
  }

  String _esc(String s) => s
      .replaceAll('&', '&amp;')
      .replaceAll('<', '&lt;')
      .replaceAll('>', '&gt;')
      .replaceAll('"', '&quot;')
      .replaceAll("'", '&#39;');

  static const _css = '''
* { margin: 0; padding: 0; box-sizing: border-box; }
body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; background: #0d1117; color: #c9d1d9; padding: 24px; }
.header { text-align: center; padding: 32px 0; }
.header h1 { font-size: 28px; color: #58a6ff; }
.header .meta { color: #8b949e; margin-top: 8px; font-size: 14px; }
.score-card { text-align: center; margin: 24px auto; padding: 24px; border-radius: 12px; max-width: 200px; }
.score-card.pass { background: #0d4429; border: 2px solid #238636; }
.score-card.warn { background: #4a3000; border: 2px solid #d29922; }
.score-card.fail { background: #490202; border: 2px solid #f85149; }
.score { font-size: 48px; font-weight: bold; }
.grade { font-size: 20px; margin-top: 4px; }
.status { font-size: 14px; margin-top: 8px; font-weight: bold; text-transform: uppercase; }
.summary { display: flex; justify-content: center; gap: 16px; margin: 24px 0; flex-wrap: wrap; }
.stat { text-align: center; padding: 16px 24px; border-radius: 8px; background: #161b22; border: 1px solid #30363d; min-width: 100px; }
.stat .num { display: block; font-size: 32px; font-weight: bold; }
.stat .label { font-size: 12px; color: #8b949e; text-transform: uppercase; }
.stat.critical .num { color: #ff4444; }
.stat.high .num { color: #f85149; }
.stat.medium .num { color: #d29922; }
.stat.low .num { color: #58a6ff; }
.stat.info .num { color: #8b949e; }
.category { margin: 32px 0; }
.category h2 { color: #58a6ff; font-size: 20px; margin-bottom: 12px; }
.category .count { color: #8b949e; font-weight: normal; }
table { width: 100%; border-collapse: collapse; background: #161b22; border-radius: 8px; overflow: hidden; }
th { background: #21262d; color: #8b949e; padding: 10px 12px; text-align: left; font-size: 12px; text-transform: uppercase; }
td { padding: 10px 12px; border-top: 1px solid #21262d; font-size: 13px; }
.badge { padding: 2px 8px; border-radius: 4px; font-size: 11px; font-weight: bold; }
.badge.critical { background: #ff4444; color: #fff; }
.badge.high { background: #f85149; color: #fff; }
.badge.medium { background: #d29922; color: #000; }
.badge.low { background: #58a6ff; color: #000; }
.badge.info { background: #484f58; color: #c9d1d9; }
.no-findings { text-align: center; padding: 48px; color: #238636; font-size: 20px; }
.footer { text-align: center; padding: 32px 0; color: #484f58; font-size: 12px; }
''';
}
